[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py312"
lint.extend-select = ["I"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-q --import-mode=importlib --tb=line"
testpaths = ["2025"]




